/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module counter4(clk, rst_n, q3, q2, q1, q0);
  wire _0_;
  wire [3:0] _1_;
  reg [3:0] _2_;
  input clk;
  wire clk;
  wire [3:0] count_r;
  output q0;
  wire q0;
  output q1;
  wire q1;
  output q2;
  wire q2;
  output q3;
  wire q3;
  input rst_n;
  wire rst_n;
  assign _0_ = ~ rst_n;
  assign _1_ = count_r + 4'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) _2_ <= 4'h0;
    else _2_ <= _1_;
  assign count_r = _2_;
  assign q3 = count_r[3];
  assign q2 = count_r[2];
  assign q1 = count_r[1];
  assign q0 = count_r[0];
endmodule
